# Generated by Django 4.2 on 2026-05-27 16:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hojitas', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='hoja',
            name='descripcion',
            field=models.TextField(null=True, verbose_name='Descripción'),
        ),
        migrations.AddField(
            model_name='hoja',
            name='imagen',
            field=models.ImageField(null=True, upload_to='imagenes/', verbose_name='Imagen'),
        ),
        migrations.AddField(
            model_name='hoja',
            name='nombre',
            field=models.CharField(default=None, max_length=100, verbose_name='Nombre'),
        ),
        migrations.AddField(
            model_name='hoja',
            name='precio',
            field=models.PositiveIntegerField(default=0, verbose_name='Precio'),
        ),
    ]
